import { Inter } from "next/font/google";
import "./globals.css";
import MyProvider from "./context/MyContext";
import ProgressProvider from "./ProgressProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "skailama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProgressProvider>
          <MyProvider>{children}</MyProvider>
        </ProgressProvider>
      </body>
    </html>
  );
}
